# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/abatts/Desktop/Game Dev/2DGame2021"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/abatts/Desktop/Game Dev/2DGame2021"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/abatts/Desktop/Game Dev/2DGame2021/CMakeFiles" "/home/abatts/Desktop/Game Dev/2DGame2021/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/abatts/Desktop/Game Dev/2DGame2021/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named 2DGame2021_core

# Build rule for target.
2DGame2021_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 2DGame2021_core
.PHONY : 2DGame2021_core

# fast build rule for target.
2DGame2021_core/fast:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/build
.PHONY : 2DGame2021_core/fast

bin/main.o: bin/main.cpp.o

.PHONY : bin/main.o

# target to build an object file
bin/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bin/main.cpp.o
.PHONY : bin/main.cpp.o

bin/main.i: bin/main.cpp.i

.PHONY : bin/main.i

# target to preprocess a source file
bin/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bin/main.cpp.i
.PHONY : bin/main.cpp.i

bin/main.s: bin/main.cpp.s

.PHONY : bin/main.s

# target to generate assembly for a file
bin/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bin/main.cpp.s
.PHONY : bin/main.cpp.s

src/button.o: src/button.cpp.o

.PHONY : src/button.o

# target to build an object file
src/button.cpp.o:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/button.cpp.o
.PHONY : src/button.cpp.o

src/button.i: src/button.cpp.i

.PHONY : src/button.i

# target to preprocess a source file
src/button.cpp.i:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/button.cpp.i
.PHONY : src/button.cpp.i

src/button.s: src/button.cpp.s

.PHONY : src/button.s

# target to generate assembly for a file
src/button.cpp.s:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/button.cpp.s
.PHONY : src/button.cpp.s

src/character.o: src/character.cpp.o

.PHONY : src/character.o

# target to build an object file
src/character.cpp.o:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/character.cpp.o
.PHONY : src/character.cpp.o

src/character.i: src/character.cpp.i

.PHONY : src/character.i

# target to preprocess a source file
src/character.cpp.i:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/character.cpp.i
.PHONY : src/character.cpp.i

src/character.s: src/character.cpp.s

.PHONY : src/character.s

# target to generate assembly for a file
src/character.cpp.s:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/character.cpp.s
.PHONY : src/character.cpp.s

src/keyboard_control.o: src/keyboard_control.cpp.o

.PHONY : src/keyboard_control.o

# target to build an object file
src/keyboard_control.cpp.o:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/keyboard_control.cpp.o
.PHONY : src/keyboard_control.cpp.o

src/keyboard_control.i: src/keyboard_control.cpp.i

.PHONY : src/keyboard_control.i

# target to preprocess a source file
src/keyboard_control.cpp.i:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/keyboard_control.cpp.i
.PHONY : src/keyboard_control.cpp.i

src/keyboard_control.s: src/keyboard_control.cpp.s

.PHONY : src/keyboard_control.s

# target to generate assembly for a file
src/keyboard_control.cpp.s:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/keyboard_control.cpp.s
.PHONY : src/keyboard_control.cpp.s

src/main_character.o: src/main_character.cpp.o

.PHONY : src/main_character.o

# target to build an object file
src/main_character.cpp.o:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/main_character.cpp.o
.PHONY : src/main_character.cpp.o

src/main_character.i: src/main_character.cpp.i

.PHONY : src/main_character.i

# target to preprocess a source file
src/main_character.cpp.i:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/main_character.cpp.i
.PHONY : src/main_character.cpp.i

src/main_character.s: src/main_character.cpp.s

.PHONY : src/main_character.s

# target to generate assembly for a file
src/main_character.cpp.s:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/main_character.cpp.s
.PHONY : src/main_character.cpp.s

src/sprite_sheet.o: src/sprite_sheet.cpp.o

.PHONY : src/sprite_sheet.o

# target to build an object file
src/sprite_sheet.cpp.o:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/sprite_sheet.cpp.o
.PHONY : src/sprite_sheet.cpp.o

src/sprite_sheet.i: src/sprite_sheet.cpp.i

.PHONY : src/sprite_sheet.i

# target to preprocess a source file
src/sprite_sheet.cpp.i:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/sprite_sheet.cpp.i
.PHONY : src/sprite_sheet.cpp.i

src/sprite_sheet.s: src/sprite_sheet.cpp.s

.PHONY : src/sprite_sheet.s

# target to generate assembly for a file
src/sprite_sheet.cpp.s:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/sprite_sheet.cpp.s
.PHONY : src/sprite_sheet.cpp.s

src/state_controller.o: src/state_controller.cpp.o

.PHONY : src/state_controller.o

# target to build an object file
src/state_controller.cpp.o:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/state_controller.cpp.o
.PHONY : src/state_controller.cpp.o

src/state_controller.i: src/state_controller.cpp.i

.PHONY : src/state_controller.i

# target to preprocess a source file
src/state_controller.cpp.i:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/state_controller.cpp.i
.PHONY : src/state_controller.cpp.i

src/state_controller.s: src/state_controller.cpp.s

.PHONY : src/state_controller.s

# target to generate assembly for a file
src/state_controller.cpp.s:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/state_controller.cpp.s
.PHONY : src/state_controller.cpp.s

src/state_menu.o: src/state_menu.cpp.o

.PHONY : src/state_menu.o

# target to build an object file
src/state_menu.cpp.o:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/state_menu.cpp.o
.PHONY : src/state_menu.cpp.o

src/state_menu.i: src/state_menu.cpp.i

.PHONY : src/state_menu.i

# target to preprocess a source file
src/state_menu.cpp.i:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/state_menu.cpp.i
.PHONY : src/state_menu.cpp.i

src/state_menu.s: src/state_menu.cpp.s

.PHONY : src/state_menu.s

# target to generate assembly for a file
src/state_menu.cpp.s:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/state_menu.cpp.s
.PHONY : src/state_menu.cpp.s

src/state_playing.o: src/state_playing.cpp.o

.PHONY : src/state_playing.o

# target to build an object file
src/state_playing.cpp.o:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/state_playing.cpp.o
.PHONY : src/state_playing.cpp.o

src/state_playing.i: src/state_playing.cpp.i

.PHONY : src/state_playing.i

# target to preprocess a source file
src/state_playing.cpp.i:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/state_playing.cpp.i
.PHONY : src/state_playing.cpp.i

src/state_playing.s: src/state_playing.cpp.s

.PHONY : src/state_playing.s

# target to generate assembly for a file
src/state_playing.cpp.s:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/state_playing.cpp.s
.PHONY : src/state_playing.cpp.s

src/user_view.o: src/user_view.cpp.o

.PHONY : src/user_view.o

# target to build an object file
src/user_view.cpp.o:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/user_view.cpp.o
.PHONY : src/user_view.cpp.o

src/user_view.i: src/user_view.cpp.i

.PHONY : src/user_view.i

# target to preprocess a source file
src/user_view.cpp.i:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/user_view.cpp.i
.PHONY : src/user_view.cpp.i

src/user_view.s: src/user_view.cpp.s

.PHONY : src/user_view.s

# target to generate assembly for a file
src/user_view.cpp.s:
	$(MAKE) -f CMakeFiles/2DGame2021_core.dir/build.make CMakeFiles/2DGame2021_core.dir/src/user_view.cpp.s
.PHONY : src/user_view.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... 2DGame2021_core"
	@echo "... bin/main.o"
	@echo "... bin/main.i"
	@echo "... bin/main.s"
	@echo "... src/button.o"
	@echo "... src/button.i"
	@echo "... src/button.s"
	@echo "... src/character.o"
	@echo "... src/character.i"
	@echo "... src/character.s"
	@echo "... src/keyboard_control.o"
	@echo "... src/keyboard_control.i"
	@echo "... src/keyboard_control.s"
	@echo "... src/main_character.o"
	@echo "... src/main_character.i"
	@echo "... src/main_character.s"
	@echo "... src/sprite_sheet.o"
	@echo "... src/sprite_sheet.i"
	@echo "... src/sprite_sheet.s"
	@echo "... src/state_controller.o"
	@echo "... src/state_controller.i"
	@echo "... src/state_controller.s"
	@echo "... src/state_menu.o"
	@echo "... src/state_menu.i"
	@echo "... src/state_menu.s"
	@echo "... src/state_playing.o"
	@echo "... src/state_playing.i"
	@echo "... src/state_playing.s"
	@echo "... src/user_view.o"
	@echo "... src/user_view.i"
	@echo "... src/user_view.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

